version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imcdata
    image: yknam/imcdata
    volumes:
      - ./src:/app/src
    ports:
      - "7009:80"
